name: Automerge

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  check_run:
    types:
      - completed
  status: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  automerge:
    permissions:
      contents: 'write'
      id-token: 'write'
    environment: local
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Info
        run: |
          echo "Running automerge workflow"
          echo ${{ secrets.DIAGRID_BOT_APPLICATION_ID }} | base64

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}

      - id: automerge
        name: Auto merge PR
        env:
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
