name: Automerge

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  check_run:
    types:
      - completed
  status: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  automerge:
    environment: local
    runs-on: "runs-on=${{ github.run_id }}/runner=regular/tag=automerge"
    if: contains(github.event.pull_request.labels.*.name, 'automerge')
    needs: merge-checker
    steps:
      - uses: runs-on/action@v1 # required for runs-on magic cache https://runs-on.com/caching/magic-cache/
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}
          organization: diagridio

      - id: automerge
        name: Auto merge PR
        uses: "pascalgn/automerge-action@v0.16.4"
        env:
          MERGE_REQUIRED_APPROVALS: 1
          GITHUB_TOKEN: "${{ steps.get_workflow_token.outputs.token }}"
          MERGE_RETRIES: "12"
          MERGE_RETRY_SLEEP: "10000"
          MERGE_METHOD: "squash"
