name: Diagrid Bot

on:
  issue_comment:
    types: [created]
  issues:
    types: [labeled]
  check_suite:
    types:
      - completed
  check_run:
    types:
      - created
      - rerequested
      - completed
      - requested_action
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

jobs:
  diagrid-bot:
    name: bot-processor
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
      checks: 'write'
    environment: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # required to make the script available for next step

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}

      - name: Comment analyzer
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          script: |
            const script = require('./.github/scripts/diagrid-bot.js')
            await script({github, context})
