name: Merge Checker

on:
  workflow_dispatch:

jobs:
  checker:
    environment: local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}

      - name: Checker
        id: merge-checker
        run: |
          echo "Testing Merge Checker"
          echo "Token: ${{ steps.get_workflow_token.outputs.token }}"
          echo "Event: ${{ github.event_name }}"
          echo "Pull Request: ${{ github.event.pull_request.number }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"


      - name: Update check
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          script: |
            const checkRun = await github.rest.checks.update({
              ...context.repo,
              name: 'Merge Checker',
              head_sha: context.sha,
              status: 'completed',
              conclusion: 'success',
              output: {
                title: 'Merge Checker',
                summary: 'Merge Checker completed successfully.',
                text: `Event: ${context.eventName}\nPull Request: ${context.payload.pull_request.number}\nLabels: ${JSON.stringify(context.payload.pull_request.labels)}`
              }
            });
            console.log('Check run created:', checkRun.data);

