name: Merge Checker

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  check_run:
    types:
      - completed
  status: {}

jobs:
  checker:
    environment: local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}

      - name: Checker
        id: merge-checker
        run: |
          echo "Testing Merge Checker"
          echo "Token: ${{ steps.get_workflow_token.outputs.token }}"
          echo "Event: ${{ github.event_name }}"
          echo "Check run id: ${{ github.event.inputs.check-run-id }}"
          echo "Check run status: ${{ github.event.inputs.check-run-status }}"
          echo "Check run conclusion: ${{ github.event.inputs.check-run-conclusion }}"
          sleep 30
          exit 0

      # - name: Update check
      #   uses: actions/github-script@v7
      #   with:
      #     github-token: ${{ steps.get_workflow_token.outputs.token }}
      #     script: |
      #       await github.rest.checks.update({
      #         ...context.repo,
      #         check_run_id: ${{ github.event.inputs.check-run-id }},
      #         head_sha: context.sha,
      #         status: "${{ github.event.inputs.check-run-status }}",
      #         conclusion: "${{ github.event.inputs.check-run-conclusion }}",
      #         output: {
      #           title: 'Merge Checker',
      #           summary: 'Merge Checker completed successfully.',
      #           text: `Event: ${context.eventName}\n}`
      #         }
      #       });

