name: Merge Checker Scheduler

on:
  # schedule:
  #   - cron: '*/1 * * * *'  # Runs every 1 minute
  workflow_dispatch:       # Allow manual triggering

jobs:
  check-all-prs:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
      checks: read
      actions: write

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}

      - name: Find in-progress check runs
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          debug: false
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
            });

            for (const pr of pulls) {
              console.log(`🔍 Checking PR #${pr.number} with SHA ${pr.head.sha}`);

              const runs = await github.rest.actions.listWorkflowRuns({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'merge-checker.yaml', // can also be numeric ID
                branch: pr.head.ref,
              });
              const latestRun = runs.data.workflow_runs[0];
              if (!latestRun) {
                console.log(`❌ No in-progress workflow run found for PR #${pr.number}`);
                continue; // Skip to the next PR if no in-progress run
              }

              console.log(`🟡 Found merge-checker workflow run: ${latestRun.id} (${latestRun.name} (${latestRun.status} / ${latestRun.conclusion}))`);
              // Check if the latest run is in progress, if so move on
              if (latestRun.status == 'in_progress') {
                console.log(`✅ Workflow already in progress for PR #${pr.number}`);
                continue; // Skip to the next PR if already in progress
              }

              // If the latest run is successful, move on
              if (latestRun.status === 'completed' && latestRun.conclusion === 'success') {
                console.log(`✅ Workflow already completed successfully for PR #${pr.number}`);
                continue; // Skip to the next PR if already completed successfully
              }

              // Otherwise, re-run the workflow
              await github.rest.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: latestRun.id,
              });
              console.log(`🔄 Re-running merge-checker workflow for PR #${pr.number}`);
            }

