name: Test

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted

jobs:
  test:
    environment: local
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v2
        with:
          application_id: ${{ secrets.DIAGRID_BOT_APPLICATION_ID }}
          application_private_key: ${{ secrets.DIAGRID_BOT_APPLICATION_PRIVATE_KEY }}
      - name: Test
        id: test
        run: |
          echo "Testing automerge workflow"
          echo "Token: ${{ steps.get_workflow_token.outputs.token }}"
          echo "Event: ${{ github.event_name }}"
          echo "Pull Request: ${{ github.event.pull_request.number }}"
          echo "Labels: ${{ toJson(github.event.pull_request.labels) }}"


